# Generated by Django 5.1.5 on 2025-01-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
