# Generated by Django 5.1.5 on 2025-01-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_artigo_data_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
